/** "Free trial key" form (ordem 05/10 §1.2): e-mail → POST /v1/keys/trial → shows the key and stores it in this browser (dsi_key). */
export function trialForm(pt: boolean): string {
  const t = pt ? { h: "Chave de teste grátis", p: "200 chamadas por 7 dias, sem cartão. Vale para o Carry Data e o feed de eventos (não inclui o oráculo).", b: "Chave de teste grátis (200 chamadas)", ok: "Sua chave (aparece uma vez — guarde):", saved: "Já salva neste navegador.", err: "Não foi possível gerar:" }
    : { h: "Free trial key", p: "200 calls for 7 days, no card. Carry Data and the event feed (not the oracle).", b: "Free trial key (200 calls)", ok: "Your key (shown once — store it):", saved: "Saved in this browser.", err: "Could not create it:" };
  return `<div class="box" id="trial" style="border:1px solid #2b3a55;border-radius:14px;padding:16px;margin:16px 0;background:#0f1622"><h3 style="margin:0 0 6px">${t.h}</h3><p style="margin:0 0 10px;color:#9aa0a6">${t.p}</p>
<form id="trialf" style="display:flex;gap:8px;flex-wrap:wrap"><input name="email" type="email" required placeholder="you@example.com" style="flex:1;min-width:220px;padding:10px;border-radius:8px;border:1px solid #2a2f36;background:#0b0d10;color:#e8eaed">
<button type="submit" style="background:#22c55e;color:#04120a;border:0;border-radius:10px;padding:10px 16px;font-weight:700;cursor:pointer">${t.b}</button></form><div id="trialout" style="margin-top:10px;word-break:break-all"></div></div>
<script>(function(){var f=document.getElementById("trialf");if(!f)return;f.onsubmit=async function(e){e.preventDefault();var o=document.getElementById("trialout");o.textContent="…";try{var r=await fetch("/v1/keys/trial",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:new FormData(f).get("email")})});var j=await r.json();if(r.ok&&j.api_key){try{localStorage.setItem("dsi_key",j.api_key)}catch(_){}o.innerHTML="${t.ok} <code style=\\"background:#151a21;padding:4px 6px;border-radius:6px\\">"+j.api_key+"</code><br><small>${t.saved} "+j.calls+" calls · "+String(j.expires_at).slice(0,10)+" · X-API-KEY</small>"}else{o.textContent="${t.err} "+(j.error||r.status)}}catch(x){o.textContent="${t.err} "+x}}})();</script>`;
}
