/**
 * Exposure graph seed. Node ids are typed: company:NVDA, asset:NVDA, country:TW, commodity:CL,
 * regulator:FTC, facility:TSMC-FAB12, sector:semis, index:NDX, protocol:..., person:...
 *
 * Edge: from → to, with weight (0..1 = how much of `to` is explained by `from`) and sign
 * (+1: good for `from` is good for `to`; -1: inverse). Impact propagates along edge direction.
 *
 * Every asset in the universe implicitly has company:X → asset:X (weight 1, +1) and
 * tag-derived edges (see graph.ts) so this file only carries what tags can't express.
 */
export type EdgeType =
  | "supplies" | "revenue_from" | "input" | "regulated_by" | "correlated" | "constituent"
  | "located_in" | "competes" | "holds" | "pegged" | "sector_of" | "operates" | "exposed_to";

export interface Edge { from: string; to: string; type: EdgeType; w: number; sign: 1 | -1; note?: string }
export interface Facility { id: string; name: string; company: string; country: string; lat: number; lng: number; critical: number }

export const FACILITIES: Facility[] = [
  { id: "TSMC-FAB12", name: "TSMC Fab 12 Hsinchu", company: "TSM", country: "TW", lat: 24.774, lng: 120.992, critical: 1 },
  { id: "TSMC-FAB18", name: "TSMC Fab 18 Tainan (3nm/5nm)", company: "TSM", country: "TW", lat: 23.111, lng: 120.273, critical: 1 },
  { id: "TSMC-AZ", name: "TSMC Arizona", company: "TSM", country: "US", lat: 33.68, lng: -112.13, critical: 0.5 },
  { id: "SAMSUNG-PYEONGTAEK", name: "Samsung Pyeongtaek", company: "SAMSUNG", country: "KR", lat: 37.05, lng: 127.07, critical: 0.8 },
  { id: "SKHYNIX-ICHEON", name: "SK Hynix Icheon (HBM)", company: "SKHYNIX", country: "KR", lat: 37.256, lng: 127.483, critical: 0.9 },
  { id: "MU-BOISE", name: "Micron Boise", company: "MU", country: "US", lat: 43.53, lng: -116.12, critical: 0.6 },
  { id: "INTC-CHANDLER", name: "Intel Ocotillo Chandler", company: "INTC", country: "US", lat: 33.25, lng: -111.83, critical: 0.6 },
  { id: "TSLA-FREMONT", name: "Tesla Fremont", company: "TSLA", country: "US", lat: 37.49, lng: -121.94, critical: 0.6 },
  { id: "TSLA-SHANGHAI", name: "Tesla Giga Shanghai", company: "TSLA", country: "CN", lat: 30.87, lng: 121.79, critical: 0.8 },
  { id: "TSLA-AUSTIN", name: "Tesla Giga Texas", company: "TSLA", country: "US", lat: 30.22, lng: -97.62, critical: 0.6 },
  { id: "TSLA-BERLIN", name: "Tesla Giga Berlin", company: "TSLA", country: "DE", lat: 52.39, lng: 13.79, critical: 0.5 },
  { id: "AAPL-ZHENGZHOU", name: "Foxconn Zhengzhou (iPhone City)", company: "AAPL", country: "CN", lat: 34.72, lng: 113.82, critical: 0.9 },
  { id: "AAPL-CHENNAI", name: "Foxconn Sriperumbudur", company: "AAPL", country: "IN", lat: 12.96, lng: 79.94, critical: 0.5 },
  { id: "AMZN-USEAST1", name: "AWS us-east-1 N. Virginia", company: "AMZN", country: "US", lat: 39.04, lng: -77.49, critical: 0.9 },
  { id: "MSFT-QUINCY", name: "Azure Quincy WA", company: "MSFT", country: "US", lat: 47.23, lng: -119.85, critical: 0.5 },
  { id: "BA-EVERETT", name: "Boeing Everett", company: "BA", country: "US", lat: 47.92, lng: -122.28, critical: 0.8 },
  { id: "BA-RENTON", name: "Boeing Renton (737)", company: "BA", country: "US", lat: 47.49, lng: -122.21, critical: 0.8 },
  { id: "XOM-BAYTOWN", name: "ExxonMobil Baytown refinery", company: "XOM", country: "US", lat: 29.74, lng: -95.01, critical: 0.6 },
  { id: "PORT-HOUSTON", name: "Port of Houston / Ship Channel", company: "XLE", country: "US", lat: 29.73, lng: -95.02, critical: 0.7 },
  { id: "HORMUZ", name: "Strait of Hormuz", company: "CL", country: "IR", lat: 26.57, lng: 56.25, critical: 1 },
  { id: "SUEZ", name: "Suez Canal", company: "CL", country: "EG", lat: 30.46, lng: 32.35, critical: 0.7 },
  { id: "TAIWAN-STRAIT", name: "Taiwan Strait", company: "TSM", country: "TW", lat: 24.5, lng: 119.5, critical: 1 },
  { id: "RAS-TANURA", name: "Ras Tanura (Aramco)", company: "CL", country: "SA", lat: 26.64, lng: 50.16, critical: 0.9 },
  { id: "ABQAIQ", name: "Abqaiq processing", company: "CL", country: "SA", lat: 25.94, lng: 49.67, critical: 0.9 },
  { id: "LNG-SABINE", name: "Sabine Pass LNG", company: "NG", country: "US", lat: 29.74, lng: -93.87, critical: 0.6 },
  { id: "FCX-GRASBERG", name: "Grasberg mine", company: "FCX", country: "ID", lat: -4.05, lng: 137.11, critical: 0.9 },
  { id: "ODESA-PORT", name: "Odesa grain port", company: "ZW", country: "UA", lat: 46.48, lng: 30.73, critical: 0.6 },
  { id: "NYSE", name: "NYSE / NJ datacenters (Mahwah)", company: "SPX", country: "US", lat: 41.09, lng: -74.14, critical: 0.5 },
];

export const EDGES: Edge[] = [
  // --- Semis supply chain
  { from: "company:TSM", to: "company:NVDA", type: "supplies", w: 0.9, sign: 1, note: "all leading-edge GPUs" },
  { from: "company:TSM", to: "company:AMD", type: "supplies", w: 0.9, sign: 1 },
  { from: "company:TSM", to: "company:AAPL", type: "supplies", w: 0.8, sign: 1, note: "A/M-series SoCs" },
  { from: "company:TSM", to: "company:AVGO", type: "supplies", w: 0.7, sign: 1 },
  { from: "company:TSM", to: "company:QCOM", type: "supplies", w: 0.7, sign: 1 },
  { from: "company:TSM", to: "asset:SMH", type: "constituent", w: 0.6, sign: 1 },
  { from: "company:SKHYNIX", to: "company:NVDA", type: "supplies", w: 0.6, sign: 1, note: "HBM" },
  { from: "company:SAMSUNG", to: "company:NVDA", type: "supplies", w: 0.3, sign: 1 },
  { from: "company:NVDA", to: "company:SMCI", type: "supplies", w: 0.8, sign: 1 },
  { from: "company:NVDA", to: "company:DELL", type: "supplies", w: 0.4, sign: 1 },
  { from: "company:NVDA", to: "company:MSFT", type: "supplies", w: 0.3, sign: 1, note: "capex dependence, mixed" },
  { from: "company:MSFT", to: "company:NVDA", type: "revenue_from", w: 0.2, sign: 1 },
  { from: "company:META", to: "company:NVDA", type: "revenue_from", w: 0.15, sign: 1 },
  { from: "company:AMZN", to: "company:NVDA", type: "revenue_from", w: 0.15, sign: 1 },
  { from: "company:GOOG", to: "company:NVDA", type: "revenue_from", w: 0.1, sign: 1 },
  { from: "company:ORCL", to: "company:NVDA", type: "revenue_from", w: 0.1, sign: 1 },
  { from: "company:NVDA", to: "company:AMD", type: "competes", w: 0.4, sign: -1 },
  { from: "company:ARM", to: "company:QCOM", type: "supplies", w: 0.3, sign: 1 },
  { from: "company:NVDA", to: "asset:NDX", type: "constituent", w: 0.09, sign: 1 },
  { from: "company:NVDA", to: "asset:SPX", type: "constituent", w: 0.07, sign: 1 },
  { from: "company:AAPL", to: "asset:NDX", type: "constituent", w: 0.08, sign: 1 },
  { from: "company:MSFT", to: "asset:NDX", type: "constituent", w: 0.08, sign: 1 },
  { from: "company:AMZN", to: "asset:NDX", type: "constituent", w: 0.05, sign: 1 },
  { from: "company:META", to: "asset:NDX", type: "constituent", w: 0.04, sign: 1 },
  { from: "company:GOOG", to: "asset:NDX", type: "constituent", w: 0.05, sign: 1 },
  { from: "company:TSLA", to: "asset:NDX", type: "constituent", w: 0.03, sign: 1 },
  { from: "company:AVGO", to: "asset:NDX", type: "constituent", w: 0.04, sign: 1 },
  { from: "asset:NDX", to: "asset:QQQ", type: "pegged", w: 1, sign: 1 },
  { from: "asset:SPX", to: "asset:SPY", type: "pegged", w: 1, sign: 1 },
  { from: "asset:SPX", to: "asset:VIX", type: "correlated", w: 0.8, sign: -1 },

  // --- Taiwan / China geopolitics
  { from: "country:TW", to: "company:TSM", type: "located_in", w: 1, sign: 1 },
  { from: "country:TW", to: "asset:SMH", type: "exposed_to", w: 0.6, sign: 1 },
  { from: "country:CN", to: "company:AAPL", type: "revenue_from", w: 0.19, sign: 1 },
  { from: "country:CN", to: "company:TSLA", type: "revenue_from", w: 0.22, sign: 1 },
  { from: "country:CN", to: "company:NVDA", type: "revenue_from", w: 0.13, sign: 1 },
  { from: "country:CN", to: "company:QCOM", type: "revenue_from", w: 0.45, sign: 1 },
  { from: "country:CN", to: "company:NKE", type: "revenue_from", w: 0.15, sign: 1 },
  { from: "country:CN", to: "company:SBUX", type: "revenue_from", w: 0.1, sign: 1 },
  { from: "country:CN", to: "company:CAT", type: "revenue_from", w: 0.08, sign: 1 },
  { from: "country:CN", to: "company:BABA", type: "located_in", w: 1, sign: 1 },
  { from: "country:CN", to: "company:PDD", type: "located_in", w: 1, sign: 1 },
  { from: "country:CN", to: "company:NIO", type: "located_in", w: 1, sign: 1 },
  { from: "country:CN", to: "commodity:HG", type: "exposed_to", w: 0.5, sign: 1, note: "~55% of copper demand" },
  { from: "country:CN", to: "commodity:ZS", type: "exposed_to", w: 0.4, sign: 1 },
  { from: "country:CN", to: "asset:USDCNH", type: "exposed_to", w: 0.8, sign: -1 },

  // --- Energy / Middle East
  { from: "country:IR", to: "commodity:CL", type: "exposed_to", w: 0.6, sign: -1, note: "conflict → oil up" },
  { from: "country:SA", to: "commodity:CL", type: "exposed_to", w: 0.7, sign: -1 },
  { from: "country:IL", to: "commodity:CL", type: "exposed_to", w: 0.3, sign: -1 },
  { from: "country:RU", to: "commodity:CL", type: "exposed_to", w: 0.4, sign: -1 },
  { from: "country:RU", to: "commodity:NG", type: "exposed_to", w: 0.3, sign: -1 },
  { from: "country:RU", to: "commodity:ZW", type: "exposed_to", w: 0.4, sign: -1 },
  { from: "country:UA", to: "commodity:ZW", type: "exposed_to", w: 0.4, sign: -1 },
  { from: "commodity:CL", to: "commodity:BZ", type: "correlated", w: 0.95, sign: 1 },
  { from: "commodity:CL", to: "asset:USO", type: "pegged", w: 1, sign: 1 },
  { from: "commodity:CL", to: "asset:XLE", type: "input", w: 0.7, sign: 1 },
  { from: "commodity:CL", to: "company:XOM", type: "input", w: 0.6, sign: 1 },
  { from: "commodity:CL", to: "company:CVX", type: "input", w: 0.6, sign: 1 },
  { from: "commodity:CL", to: "company:OXY", type: "input", w: 0.8, sign: 1 },
  { from: "commodity:CL", to: "company:SLB", type: "input", w: 0.5, sign: 1 },
  { from: "commodity:CL", to: "company:AAL", type: "input", w: 0.5, sign: -1 },
  { from: "commodity:CL", to: "company:DAL", type: "input", w: 0.5, sign: -1 },
  { from: "commodity:CL", to: "company:UAL", type: "input", w: 0.5, sign: -1 },
  { from: "commodity:CL", to: "company:CCL", type: "input", w: 0.3, sign: -1 },
  { from: "commodity:CL", to: "asset:US10Y", type: "correlated", w: 0.2, sign: 1, note: "inflation expectations → yields up" },
  { from: "commodity:NG", to: "asset:UNG", type: "pegged", w: 1, sign: 1 },
  { from: "commodity:NG", to: "company:VST", type: "input", w: 0.3, sign: 1 },
  { from: "commodity:GC", to: "asset:GLD", type: "pegged", w: 1, sign: 1 },
  { from: "commodity:GC", to: "company:NEM", type: "input", w: 0.8, sign: 1 },
  { from: "commodity:SI", to: "asset:SLV", type: "pegged", w: 1, sign: 1 },
  { from: "commodity:HG", to: "company:FCX", type: "input", w: 0.8, sign: 1 },

  // --- Rates / Fed / USD
  { from: "regulator:FED", to: "asset:US2Y", type: "regulated_by", w: 0.9, sign: 1 },
  { from: "regulator:FED", to: "asset:US10Y", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:FED", to: "asset:DXY", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "asset:US10Y", to: "asset:TLT", type: "pegged", w: 1, sign: -1 },
  { from: "asset:US10Y", to: "asset:NDX", type: "correlated", w: 0.4, sign: -1 },
  { from: "asset:US10Y", to: "commodity:GC", type: "correlated", w: 0.4, sign: -1 },
  { from: "asset:US10Y", to: "company:NEE", type: "correlated", w: 0.3, sign: -1 },
  { from: "asset:US10Y", to: "company:HD", type: "correlated", w: 0.3, sign: -1 },
  { from: "asset:US2Y", to: "asset:XLF", type: "correlated", w: 0.3, sign: 1 },
  { from: "asset:DXY", to: "asset:BTC", type: "correlated", w: 0.4, sign: -1 },
  { from: "asset:DXY", to: "commodity:GC", type: "correlated", w: 0.5, sign: -1 },
  { from: "asset:DXY", to: "asset:EURUSD", type: "pegged", w: 1, sign: -1 },
  { from: "regulator:ECB", to: "asset:EURUSD", type: "regulated_by", w: 0.7, sign: 1 },
  { from: "regulator:BOJ", to: "asset:USDJPY", type: "regulated_by", w: 0.7, sign: -1 },
  { from: "regulator:BCB", to: "asset:USDBRL", type: "regulated_by", w: 0.7, sign: -1 },
  { from: "regulator:PBOC", to: "asset:USDCNH", type: "regulated_by", w: 0.7, sign: -1 },
  { from: "asset:USDJPY", to: "asset:NDX", type: "correlated", w: 0.2, sign: 1, note: "carry unwind risk" },
  { from: "asset:VIX", to: "asset:BTC", type: "correlated", w: 0.3, sign: -1 },

  // --- Crypto
  { from: "asset:BTC", to: "company:MSTR", type: "holds", w: 0.9, sign: 1 },
  { from: "asset:BTC", to: "asset:IBIT", type: "pegged", w: 1, sign: 1 },
  { from: "asset:ETH", to: "asset:ETHA", type: "pegged", w: 1, sign: 1 },
  { from: "asset:BTC", to: "company:COIN", type: "correlated", w: 0.7, sign: 1 },
  { from: "asset:BTC", to: "company:HOOD", type: "correlated", w: 0.4, sign: 1 },
  { from: "asset:BTC", to: "company:MARA", type: "holds", w: 0.9, sign: 1 },
  { from: "asset:BTC", to: "company:RIOT", type: "holds", w: 0.9, sign: 1 },
  { from: "asset:BTC", to: "company:CLSK", type: "holds", w: 0.9, sign: 1 },
  { from: "asset:BTC", to: "company:SQ", type: "holds", w: 0.3, sign: 1 },
  { from: "asset:BTC", to: "company:GME", type: "holds", w: 0.2, sign: 1 },
  { from: "asset:BTC", to: "asset:ETH", type: "correlated", w: 0.8, sign: 1 },
  { from: "asset:BTC", to: "asset:SOL", type: "correlated", w: 0.75, sign: 1 },
  { from: "asset:BTC", to: "asset:DOGE", type: "correlated", w: 0.7, sign: 1 },
  { from: "asset:ETH", to: "asset:LINK", type: "correlated", w: 0.7, sign: 1 },
  { from: "asset:ETH", to: "asset:USDC", type: "operates", w: 0.2, sign: 1 },
  { from: "asset:USDT", to: "asset:BTC", type: "exposed_to", w: 0.5, sign: 1, note: "mint → liquidity; depeg → risk-off" },
  { from: "asset:BNB", to: "company:COIN", type: "competes", w: 0.2, sign: -1 },
  { from: "regulator:SEC", to: "company:COIN", type: "regulated_by", w: 0.7, sign: 1 },
  { from: "regulator:SEC", to: "asset:XRP", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:SEC", to: "asset:BTC", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:CFTC", to: "asset:BTC", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:CFTC", to: "asset:HYPE", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:FED", to: "asset:USDT", type: "regulated_by", w: 0.3, sign: 1, note: "GENIUS Act" },
  { from: "regulator:FED", to: "asset:USDC", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:FED", to: "asset:BTC", type: "regulated_by", w: 0.4, sign: 1, note: "liquidity" },
  { from: "company:COIN", to: "asset:USDC", type: "operates", w: 0.5, sign: 1 },
  { from: "asset:SOL", to: "asset:HYPE", type: "competes", w: 0.2, sign: -1 },
  { from: "asset:TON", to: "asset:TON", type: "correlated", w: 0, sign: 1 },

  // --- Regulators → sectors/companies (antitrust, FDA, FCC…)
  { from: "regulator:FTC", to: "company:META", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:FTC", to: "company:AMZN", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:FTC", to: "company:MSFT", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:DOJ", to: "company:GOOG", type: "regulated_by", w: 0.7, sign: 1 },
  { from: "regulator:DOJ", to: "company:GOOGL", type: "regulated_by", w: 0.7, sign: 1 },
  { from: "regulator:DOJ", to: "company:AAPL", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:DOJ", to: "company:V", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:DOJ", to: "company:UNH", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:EC", to: "company:META", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:EC", to: "company:AAPL", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:EC", to: "company:GOOG", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:EC", to: "company:MSFT", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:FDA", to: "company:LLY", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:FDA", to: "company:NVO", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:FDA", to: "company:PFE", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:FDA", to: "company:MRK", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:FDA", to: "company:MRNA", type: "regulated_by", w: 0.8, sign: 1 },
  { from: "regulator:FDA", to: "company:ABBV", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:FDA", to: "company:JNJ", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:NHTSA", to: "company:TSLA", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:NHTSA", to: "company:F", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:NHTSA", to: "company:GM", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:FAA", to: "company:BA", type: "regulated_by", w: 0.8, sign: 1 },
  { from: "regulator:FCC", to: "company:T", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:FCC", to: "company:VZ", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:FCC", to: "company:TMUS", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:BIS", to: "company:NVDA", type: "regulated_by", w: 0.6, sign: 1, note: "export controls" },
  { from: "regulator:BIS", to: "company:AMD", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:BIS", to: "company:AMAT", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:USTR", to: "company:WMT", type: "regulated_by", w: 0.3, sign: 1, note: "tariffs" },
  { from: "regulator:USTR", to: "company:NKE", type: "regulated_by", w: 0.4, sign: 1 },
  { from: "regulator:USTR", to: "company:PDD", type: "regulated_by", w: 0.5, sign: 1 },
  { from: "regulator:USTR", to: "company:AAPL", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:USTR", to: "company:GM", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:USTR", to: "company:F", type: "regulated_by", w: 0.3, sign: 1 },
  { from: "regulator:CMS", to: "company:UNH", type: "regulated_by", w: 0.6, sign: 1 },
  { from: "regulator:OFAC", to: "asset:USDT", type: "regulated_by", w: 0.3, sign: 1 },

  // --- Weather / catastrophe
  { from: "country:US-GULF", to: "commodity:NG", type: "exposed_to", w: 0.4, sign: -1 },
  { from: "country:US-GULF", to: "commodity:CL", type: "exposed_to", w: 0.3, sign: -1 },
  { from: "country:US-GULF", to: "company:ALL", type: "exposed_to", w: 0.5, sign: 1 },
  { from: "country:US-GULF", to: "company:TRV", type: "exposed_to", w: 0.5, sign: 1 },
  { from: "country:US-GULF", to: "company:HD", type: "exposed_to", w: 0.2, sign: -1, note: "rebuild demand" },
  { from: "country:US-GULF", to: "company:NEE", type: "exposed_to", w: 0.4, sign: 1 },
  { from: "country:US-GULF", to: "company:AAL", type: "exposed_to", w: 0.3, sign: 1 },
  { from: "country:US-GULF", to: "company:CCL", type: "exposed_to", w: 0.4, sign: 1 },

  // --- Sector membership (fallback propagation)
  { from: "sector:semis", to: "asset:SMH", type: "sector_of", w: 0.8, sign: 1 },
  { from: "sector:banks", to: "asset:XLF", type: "sector_of", w: 0.8, sign: 1 },
  { from: "sector:energy", to: "asset:XLE", type: "sector_of", w: 0.8, sign: 1 },
  { from: "sector:tech", to: "asset:XLK", type: "sector_of", w: 0.8, sign: 1 },
];
